### ISSUE TITLE
handle promotions display for order items price and totals in the pdf

### ISSUE THREAD

**Issue by arnofo** [Sylius/InvoicingPlugin#166]
As of now, the line item unit price displayed in the pdf is the "full" price of the line item even if the item has been discounted. (while the subtotal is discounted)

![Annotation 2019-12-12 143055](https://user-images.githubusercontent.com/10198382/70716176-1d709b00-1cec-11ea-9751-3f7036efbad8.jpg)

No mention of the promotion is made in the totals neither.

This makes the invoice incorrect and unusable from an accounting stand point.

As the `Sylius\InvoicingPlugin\Entity\LineItem` entity does not store the discountedPrice, this cannot be fixed by just editing the `pdf.html.twig` file.

I am not sure if that should be considered as a bugfix or as a new feature request, please edit this as you see fit.

**Comment by kortwotze** [comment]
I would support handling this as a bug. Not respecting adjustments is simply incorrect at the moment and in addition, the current extension behavior of this plugin makes it barely usable for accounting.

Maybe I get the time to do something about this, we will see :/

**Comment by kortwotze** [comment]
I have spent some time on this and I currently create my invoices with the undiscounted price on the line item and then have a promotion subtotal that signs the full complete discount off the subtotal - it does not look pretty, but it is financially correct.

My suggestion/solution is to create a `PromotionItem` analog to the `TaxItem` and `LineItem`, beef all items up with more information and then this should be solveable. I am not sure if I have the time for that soon, but we should stick with this issue to handle it.

**Comment by Jeroen-G** [comment]
Sylius Plus introduced loyalty purchases in addition to regular promotions. It would be great to have the promotions, including the loyalty ones, shown on the invoice.

**Comment by GregoireDucharme** [comment]
Any changes on this subject ?

**Comment by CoderMaggie** [comment]
The issue with "unit price" being different from the "price" due to promotions has been fixed.
![image](https://user-images.githubusercontent.com/13198869/144317872-00ae3688-cdf0-4ea1-9c28-03fdb049fd99.png)
The invoice is now a document that specifies what has been purchased for how much money and how much tax has been paid. This is a minimum sufficient version of an accounting document.

Adding promotions display to it (probably in the version you know from order show) I am considering a feature request, if still relevant, please reopen a separate issue for it :)
