### ISSUE TITLE
BillingData and ShopBillingData difference?

### ISSUE THREAD

**Issue by tautelis** [Sylius/InvoicingPlugin#83]
What is the difference between BillingData and ShopBillingData?
Why one is declared in `Sylius\InvoicingPlugin\DependencyInjection\Configuration` and the other is not?
Relations should point interfaces not models.

**Comment by bartoszpietrzak1994** [comment]
Hello Vytautas, 

First of all, BillingData is a Resource (for more info, please visit https://docs.sylius.com/en/1.3/components_and_bundles/components/Resource/index.html), it's placed on every invoice and delivered by a customer. As a result, the database needs to store multiple BIllingData entities.

Since it's a Resource, it needs to be configured (you need to point to the class itself, its interface, repository etc.) and that's why it's present in `Sylius\InvoicingPlugin\DependencyInjection\Configuration` file. 

On the other hand, ShopBillingData is set globally for one channel - that's why there's no need to declare repository, factory or controller for that entity and thus ShopBillingData is not a resource.

What do you mean by `Relations should point interfaces not models.`? I've checked the configuration, Invoice entity, ShopBillingDataTrait and relations are always based on interfaces.
