### ISSUE TITLE
InvoiceRepositoryInterface standardization

### ISSUE THREAD

**Issue by tautelis** [Sylius/InvoicingPlugin#95]
It seems that this plugin poorly follows Sylius standards:

1. `interface InvoiceRepository` should be called `interface InvoiceRepositoryInterface`
2. custom invoice repository class should be defined in `Configuration.php` so it is accessible in Sylius-like style by calling `sylius_invoicing_plugin.repository.invoice`
3. `Sylius\InvoicingPlugin\Repository\DoctrineInvoiceRepository` should be moved to `Sylius\InvoicingPlugin\Doctrine\ORM\InvoiceRepository`
4. Furthermore, there is no need for `DoctrineInvoiceRepository` since default `Sylius\Bundle\ResourceBundle\Doctrine\ORM\EntityRepository` has all the implementation required. Just replace `getOneByOrderNumber` with `findOneByOrderNumber`.
5. And finally, getters should start with `get` so that `$invoice->orderNumber()` becomes `$invoice->getOrderNumber()`

Or maybe it is made like this on purpose?

**Comment by maikrosenthal** [comment]
Furthermore, set the expected return values to ?InvoiceInterface for the functions 'get' and 'getOneByOrderNumber' to avoid fatal errors if no invoice was found.

**Comment by bartoszpietrzak1994** [comment]
Hello Vytautas!

The point is that Sylius itself is an enormous project when compared to any of the official plugins and hence it's much harder to try something we consider fresh and interesting there (i. e. removing the `get` word from getters). In our opinion, that's one of the plugins' advantages. Let's set the examples of RefundPlugin and RbacPlugin - their logic relies on both application events and commands while the Sylius Core does not.

Since we've decided to use a uuid as an invoice identifier instead of an incremented integer the risk of not finding the invoice in the repository is negligible. Here comes the difference between `find` and `get` word in the repository. While `find` will return an invoice or null, `get` always returns a valid object - an invoice in this case.

**Comment by Zales0123** [comment]
I totally agree with the @bartoszpietrzak1994 explanation 👍 We must remember that Sylius is developed for years and sometimes there is just no space to refactor **everything** according to the most modern standards. For example, `interface InvoiceRepository` is named this way to avoid redundant `Interface` suffix, when we can specify details of the class a little bit more in the implementation's name (like `DoctrineInvoiceRepository`). There are lot's of things that are the matter of convention and I strongly believe it's not a **really big problem** that they're not 100% consistent with Sylius' ones. For me, the bigger problem would be if we stick to the old, not-so-great-anymore conventions and coding principles only because we must keep them in a `Sylius/Sylius` repository 🚀

**Comment by bartoszpietrzak1994** [comment]
Hello @tautelis !

Please see https://github.com/Sylius/InvoicingPlugin/pull/108#issuecomment-472362854 and let us know what you think and if you are fine with closing this issue as well :)
